/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import model.FoodDonation;
import java.awt.event.ActionListener;

/**
 *
 * @author User
 */
public class CardDonasi extends javax.swing.JPanel {

    /**
     * Creates new form CardDonasi
     */
    public CardDonasi(FoodDonation donation, ActionListener onBookingClick) {
        initComponents();
        
        // Set Data ke UI (Pastikan nama variabel di Design sudah diganti!)
        lblFoodName.setText(donation.getFoodName());
        lblDonor.setText("Oleh: " + donation.getDonorName());
        lblQty.setText("Sisa: " + donation.getQuantity() + " Porsi");
        lblLokasi.setText(donation.getPickupLocation());
        
        // Aksi Tombol
        btnBooking.addActionListener(onBookingClick);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoodName = new javax.swing.JLabel();
        lblDonor = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        lblLokasi = new javax.swing.JLabel();
        btnBooking = new javax.swing.JButton();

        lblFoodName.setFont(new java.awt.Font("Lufga", 1, 14)); // NOI18N
        lblFoodName.setForeground(new java.awt.Color(0, 102, 102));
        lblFoodName.setText(" ");

        lblDonor.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        lblDonor.setForeground(new java.awt.Color(0, 102, 102));
        lblDonor.setText(" ");

        lblQty.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        lblQty.setForeground(new java.awt.Color(0, 102, 102));
        lblQty.setText(" ");

        lblLokasi.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        lblLokasi.setForeground(new java.awt.Color(0, 102, 102));
        lblLokasi.setText(" ");

        btnBooking.setBackground(new java.awt.Color(0, 102, 102));
        btnBooking.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        btnBooking.setForeground(new java.awt.Color(255, 255, 255));
        btnBooking.setText("Booking");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLokasi, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(lblDonor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnBooking)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFoodName)
                    .addComponent(btnBooking))
                .addGap(10, 10, 10)
                .addComponent(lblDonor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQty)
                .addGap(15, 15, 15)
                .addComponent(lblLokasi)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private javax.swing.JLabel lblDonor;
    private javax.swing.JLabel lblFoodName;
    private javax.swing.JLabel lblLokasi;
    private javax.swing.JLabel lblQty;
    // End of variables declaration//GEN-END:variables
}
