package view;
import model.User;
import dao.AdminDAO;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class DashboardAdmin_semuaReservasi extends javax.swing.JFrame {
    private User adminUser;
    private AdminDAO adminDAO;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAdmin_semuaReservasi.class.getName());

    /**
     * Creates new form DashboardAdmin
     */
    
    public DashboardAdmin_semuaReservasi() {
        initComponents();
        this.adminDAO = new AdminDAO();
        loadTable();
        // Jangan panggil fungsi yang butuh adminUser di sini agar tidak error NullPointer
    }
    public DashboardAdmin_semuaReservasi(User user) {
        initComponents();
        this.adminUser = user;
        this.adminDAO = new AdminDAO();
        
        loadTable();
    }
    private void loadTable() {
        // Panggil method baru dari DAO
        DefaultTableModel model = adminDAO.getAllReservations();
        tableAllReservations.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        lblReservasi = new javax.swing.JLabel();
        lblComment = new javax.swing.JLabel();
        lblDonate = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        btnLogout = new java.awt.Button();
        panel1 = new java.awt.Panel();
        labelDonasi = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAllReservations = new javax.swing.JTable();
        panel2 = new java.awt.Panel();
        Heading1 = new javax.swing.JLabel();
        bg4 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setPreferredSize(new java.awt.Dimension(223, 744));

        lblDashboard.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(138, 140, 144));
        lblDashboard.setText("Dashboard");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });

        lblReservasi.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        lblReservasi.setForeground(new java.awt.Color(138, 140, 144));
        lblReservasi.setText("Semua Reservasi");
        lblReservasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReservasiMouseClicked(evt);
            }
        });

        lblComment.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        lblComment.setForeground(new java.awt.Color(138, 140, 144));
        lblComment.setText("Semua Komentar");
        lblComment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCommentMouseClicked(evt);
            }
        });

        lblDonate.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        lblDonate.setForeground(new java.awt.Color(138, 140, 144));
        lblDonate.setText("Semua Donasi");
        lblDonate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDonateMouseClicked(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(138, 140, 144));
        lblUser.setText("Semua User");
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/SquaresFour.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/CalendarDots.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ChatTeardropDots.png"))); // NOI18N
        jLabel8.setText("jLabel6");
        jLabel8.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BowlFood.png"))); // NOI18N
        jLabel9.setText("jLabel6");
        jLabel9.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/PersonSimpleTaiChi.png"))); // NOI18N
        jLabel10.setText("jLabel6");
        jLabel10.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel10.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(20, 20));

        Logo.setForeground(new java.awt.Color(0, 175, 119));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo kicik ijo.png"))); // NOI18N

        Heading.setFont(new java.awt.Font("Lufga", 1, 20)); // NOI18N
        Heading.setForeground(new java.awt.Color(0, 175, 119));
        Heading.setText("SumbangBang");

        btnLogout.setBackground(new java.awt.Color(255, 96, 96));
        btnLogout.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setLabel("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Heading))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser)
                            .addComponent(lblDonate)
                            .addComponent(lblComment)
                            .addComponent(lblReservasi)
                            .addComponent(lblDashboard)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Heading)
                    .addComponent(Logo))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDashboard)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReservasi)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComment)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDonate)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel1.setBackground(new java.awt.Color(233, 236, 239));
        panel1.setPreferredSize(new java.awt.Dimension(910, 744));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelDonasi.setFont(new java.awt.Font("Lufga", 1, 18)); // NOI18N
        labelDonasi.setForeground(new java.awt.Color(0, 175, 119));
        labelDonasi.setName(""); // NOI18N
        labelDonasi.setText("Reservasi Terbaru");
        panel1.add(labelDonasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, -1));

        jScrollPane1.setFont(new java.awt.Font("Lufga SemiBold", 0, 14)); // NOI18N

        tableAllReservations.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        tableAllReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableAllReservations);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 860, 590));

        panel2.setBackground(new java.awt.Color(0, 175, 119));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading1.setFont(new java.awt.Font("Lufga", 1, 20)); // NOI18N
        Heading1.setForeground(new java.awt.Color(255, 255, 255));
        Heading1.setText("Semua Reservasi");
        panel2.add(Heading1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        bg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pattern.jpg"))); // NOI18N
        bg4.setText("jLabel2");
        bg4.setPreferredSize(new java.awt.Dimension(426, 82));
        panel2.add(bg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 70));

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 70));

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus Data");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        panel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, -1, -1));

        btnAdd.setBackground(new java.awt.Color(0, 153, 153));
        btnAdd.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Tambah Data");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        btnEdit1.setBackground(new java.awt.Color(0, 153, 51));
        btnEdit1.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        btnEdit1.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit1.setText("Edit Data");
        btnEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit1ActionPerformed(evt);
            }
        });
        panel1.add(btnEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 920, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblReservasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReservasiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblReservasiMouseClicked

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        // TODO add your handling code here:
        new DashboardAdmin(adminUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void lblCommentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCommentMouseClicked
        // TODO add your handling code here:
        new DashboardAdmin_semuaKomentar(adminUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCommentMouseClicked

    private void lblDonateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDonateMouseClicked
        // TODO add your handling code here:
        new DashboardAdmin_semuaDonasi(adminUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblDonateMouseClicked

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        // TODO add your handling code here:
        new DashboardAdmin_semuaUser(adminUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblUserMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        // 1. Cek apakah ada baris yang dipilih
        int selectedRow = tableAllReservations.getSelectedRow();
        
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Pilih baris yang ingin dihapus terlebih dahulu!", 
                "Peringatan", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Ambil ID dari kolom pertama (index 0)
        String id = tableAllReservations.getValueAt(selectedRow, 0).toString();

        // 3. Konfirmasi Penghapusan
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menghapus data ID: " + id + "?", 
            "Konfirmasi Hapus", 
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // 4. Panggil DAO untuk hapus
            if (adminDAO.deleteReservation(id)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                loadTable(); // Refresh tabel agar data hilang dari layar
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String donId = javax.swing.JOptionPane.showInputDialog(this, "Masukkan ID Donasi (Available):");
        if (donId == null || donId.isEmpty()) return;

        String recId = javax.swing.JOptionPane.showInputDialog(this, "Masukkan ID Penerima:");
        if (recId == null || recId.isEmpty()) return;

        if (adminDAO.createReservation(donId, recId)) {
             javax.swing.JOptionPane.showMessageDialog(this, "Reservasi berhasil dibuat!");
             loadTable();
        } else {
             javax.swing.JOptionPane.showMessageDialog(this, "Gagal. Cek ID atau Status Donasi.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit1ActionPerformed
        // TODO add your handling code here:
        // 1. Cek Baris Terpilih
        int selectedRow = tableAllReservations.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih reservasi yang ingin diedit!");
            return;
        }

        // 2. Ambil ID dan Status Saat Ini
        // Kolom: 0=ID, 1=Makanan, 2=Penerima, 3=Tgl, 4=Status, 5=PickupCode
        String id = tableAllReservations.getValueAt(selectedRow, 0).toString();
        String currentStatus = tableAllReservations.getValueAt(selectedRow, 4).toString();

        // 3. Siapkan Opsi Status (Agar tidak typo)
        Object[] statuses = {"PENDING", "CONFIRMED", "COMPLETED"};
        
        // Tampilkan Input Dialog dengan Dropdown
        String newStatus = (String) javax.swing.JOptionPane.showInputDialog(
                this,
                "Ubah Status Reservasi:",
                "Edit Status",
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                statuses,
                currentStatus); // Default selection

        // Jika user cancel
        if (newStatus == null) return;

        // 4. Panggil DAO
        if (adminDAO.updateReservationStatus(id, newStatus)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Status berhasil diupdate!");
            loadTable();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal update status.");
        }
    }//GEN-LAST:event_btnEdit1ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        // 1. Tampilkan Dialog Konfirmasi
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Anda yakin ingin keluar dari sistem?", 
            "Konfirmasi Logout", 
            javax.swing.JOptionPane.YES_NO_OPTION);
        
        // 2. Jika user memilih YES
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            // Panggil helper Navigator untuk pindah ke halaman Login
            Navigator.toLogin(this); 
            // Frame Dashboard ini otomatis di-dispose oleh Navigator.toLogin(this)
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAdmin_semuaReservasi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Heading1;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel bg4;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit1;
    private javax.swing.JButton btnHapus;
    private java.awt.Button btnLogout;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label labelDonasi;
    private javax.swing.JLabel lblComment;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDonate;
    private javax.swing.JLabel lblReservasi;
    private javax.swing.JLabel lblUser;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JTable tableAllReservations;
    // End of variables declaration//GEN-END:variables
}
