package view;
import model.User;
import dao.UserDAO;
import dao.AdminDAO;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class DashboardAdmin extends javax.swing.JFrame {
    private User adminUser;
    private AdminDAO adminDAO;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardAdmin.class.getName());

    /**
     * Creates new form DashboardAdmin
     */
    
    public DashboardAdmin() {
        initComponents();
        this.adminDAO = new AdminDAO();
        // Jangan panggil fungsi yang butuh adminUser di sini agar tidak error NullPointer
    }
    public DashboardAdmin(User user) {
        this.adminUser = user;
        this.adminDAO = new AdminDAO();
        
        initComponents(); // Digenerate oleh NetBeans
        
        // Inisialisasi Data Custom
        setupAdminProfile();
        loadStatistics();
        loadRecentActivityTable();
    }
    private void setupAdminProfile() {
        // Misal ada label nama di pojok kanan atas
        // lblAdminName.setText("Halo, " + adminUser.getName());
    }
    private void loadStatistics() {
        // Mengambil data real dari database
        int totalDonasi = adminDAO.getTotalDonations();
        int totalReservasi = adminDAO.getTotalReservations();
        int totalUser = adminDAO.getTotalUsers();

        // Set ke Label UI (Pastikan nama variabel label di Design sesuai)
        // lblTotalDonasi.setText(String.valueOf(totalDonasi));
        // lblTotalReservasi.setText(String.valueOf(totalReservasi));
        // lblTotalUser.setText(String.valueOf(totalUser));
        
        // Debugging log
        lblTotalDonasi.setText(String.valueOf(totalDonasi));
        lblTotalReservasi.setText(String.valueOf(totalReservasi));
        lblTotalUser.setText(String.valueOf(totalUser)); 
        
        System.out.println("Stats Loaded: " + totalDonasi);
    }
    private void loadRecentActivityTable() {
        // Setup model tabel
        javax.swing.table.DefaultTableModel model = adminDAO.getRecentActivities();
        
        // 2. Pasang ke Tabel (Hapus tanda // di depannya)
        tableAktivitas.setModel(model);
        // tableAktivitas.setModel(model); // Uncomment jika nama tabel di UI adalah tableAktivitas
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        lblTotalReservasi = new java.awt.Label();
        labeltotalreservasi = new java.awt.Label();
        panel4 = new java.awt.Panel();
        labeltotaluser = new java.awt.Label();
        lblTotalUser = new java.awt.Label();
        panel5 = new java.awt.Panel();
        lblTotalDonasi = new java.awt.Label();
        labeltotaldonasi = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAktivitas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setPreferredSize(new java.awt.Dimension(223, 744));

        jLabel1.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(138, 140, 144));
        jLabel1.setText("Dashboard");

        jLabel2.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(138, 140, 144));
        jLabel2.setText("Semua Reservasi");

        jLabel3.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(138, 140, 144));
        jLabel3.setText("Semua Komentar");

        jLabel4.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(138, 140, 144));
        jLabel4.setText("Semua Donasi");

        jLabel5.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(138, 140, 144));
        jLabel5.setText("Semua User");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/SquaresFour.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/CalendarDots.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ChatTeardropDots.png"))); // NOI18N
        jLabel8.setText("jLabel6");
        jLabel8.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel8.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/BowlFood.png"))); // NOI18N
        jLabel9.setText("jLabel6");
        jLabel9.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel9.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/PersonSimpleTaiChi.png"))); // NOI18N
        jLabel10.setText("jLabel6");
        jLabel10.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel10.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(20, 20));

        Logo.setForeground(new java.awt.Color(0, 175, 119));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo kicik ijo.png"))); // NOI18N

        Heading.setFont(new java.awt.Font("Lufga", 1, 20)); // NOI18N
        Heading.setForeground(new java.awt.Color(0, 175, 119));
        Heading.setText("SumbangBang");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Heading))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Heading)
                    .addComponent(Logo))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(427, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel1.setBackground(new java.awt.Color(233, 236, 239));
        panel1.setPreferredSize(new java.awt.Dimension(910, 744));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel3.setBackground(new java.awt.Color(0, 175, 119));
        panel3.setPreferredSize(new java.awt.Dimension(426, 82));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalReservasi.setFont(new java.awt.Font("Lufga", 1, 24)); // NOI18N
        lblTotalReservasi.setForeground(new java.awt.Color(255, 255, 255));
        panel3.add(lblTotalReservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        labeltotalreservasi.setFont(new java.awt.Font("Lufga", 1, 14)); // NOI18N
        labeltotalreservasi.setForeground(new java.awt.Color(255, 255, 255));
        labeltotalreservasi.setName(""); // NOI18N
        labeltotalreservasi.setText("Total Reservasi");
        panel3.add(labeltotalreservasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 120, -1));

        panel1.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        panel4.setBackground(new java.awt.Color(0, 175, 119));
        panel4.setPreferredSize(new java.awt.Dimension(862, 82));
        panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeltotaluser.setFont(new java.awt.Font("Lufga", 1, 14)); // NOI18N
        labeltotaluser.setForeground(new java.awt.Color(255, 255, 255));
        labeltotaluser.setName(""); // NOI18N
        labeltotaluser.setText("Total User");
        panel4.add(labeltotaluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 100, -1));

        lblTotalUser.setFont(new java.awt.Font("Lufga", 1, 24)); // NOI18N
        lblTotalUser.setForeground(new java.awt.Color(255, 255, 255));
        panel4.add(lblTotalUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        panel1.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        panel5.setBackground(new java.awt.Color(0, 175, 119));
        panel5.setPreferredSize(new java.awt.Dimension(426, 82));
        panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalDonasi.setFont(new java.awt.Font("Lufga", 1, 24)); // NOI18N
        lblTotalDonasi.setForeground(new java.awt.Color(255, 255, 255));
        panel5.add(lblTotalDonasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        labeltotaldonasi.setFont(new java.awt.Font("Lufga", 1, 14)); // NOI18N
        labeltotaldonasi.setForeground(new java.awt.Color(255, 255, 255));
        labeltotaldonasi.setName(""); // NOI18N
        labeltotaldonasi.setText("Total Donasi");
        panel5.add(labeltotaldonasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 100, -1));

        panel1.add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        tableAktivitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableAktivitas);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 402, 860, 260));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 920, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label labeltotaldonasi;
    private java.awt.Label labeltotalreservasi;
    private java.awt.Label labeltotaluser;
    private java.awt.Label lblTotalDonasi;
    private java.awt.Label lblTotalReservasi;
    private java.awt.Label lblTotalUser;
    private java.awt.Panel panel1;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private javax.swing.JTable tableAktivitas;
    // End of variables declaration//GEN-END:variables
}
