/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author gadin
 */
public class list_penerima extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(list_penerima.class.getName());

    /**
     * Creates new form list_penerima
     */
    public list_penerima() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        Heading_2 = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        btnLogin2 = new javax.swing.JButton();
        labelEmail1 = new javax.swing.JLabel();
        labelEmail3 = new javax.swing.JLabel();
        labelEmail4 = new javax.swing.JLabel();
        labelEmail5 = new javax.swing.JLabel();
        Heading_3 = new javax.swing.JLabel();
        labelEmail2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLogin1 = new javax.swing.JButton();
        Heading_4 = new javax.swing.JLabel();
        labelEmail6 = new javax.swing.JLabel();
        btnLogin3 = new javax.swing.JButton();
        labelEmail7 = new javax.swing.JLabel();
        labelEmail8 = new javax.swing.JLabel();
        labelEmail9 = new javax.swing.JLabel();
        labelEmail10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnLogin6 = new javax.swing.JButton();
        Heading_6 = new javax.swing.JLabel();
        labelEmail16 = new javax.swing.JLabel();
        btnLogin7 = new javax.swing.JButton();
        labelEmail17 = new javax.swing.JLabel();
        labelEmail18 = new javax.swing.JLabel();
        labelEmail19 = new javax.swing.JLabel();
        labelEmail20 = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/background.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading.setFont(new java.awt.Font("Lufga", 1, 20)); // NOI18N
        Heading.setForeground(new java.awt.Color(0, 113, 77));
        Heading.setText("Waktunya makan");
        getContentPane().add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnLogin.setBackground(new java.awt.Color(255, 213, 197));
        btnLogin.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(113, 2, 0));
        btnLogin.setText("Reservasi");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 1, true));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        Heading_2.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        Heading_2.setText("Ayam Katsu + Es teh Poci");

        labelEmail.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail.setText("Oleh: Hokben Galuh Mas");

        btnLogin2.setBackground(new java.awt.Color(0, 175, 119));
        btnLogin2.setFont(new java.awt.Font("Lufga", 1, 14)); // NOI18N
        btnLogin2.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin2.setText("Booking");
        btnLogin2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 1, true));
        btnLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin2ActionPerformed(evt);
            }
        });

        labelEmail1.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail1.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail1.setText("Jumlah:20 porsi");

        labelEmail3.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail3.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail3.setText("JL.Galuh mas");

        labelEmail4.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail4.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail4.setText("Expired:10/12/2025");

        labelEmail5.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail5.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail5.setText("Diposting 1 jam lalu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Heading_2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelEmail1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelEmail3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmail5)
                            .addComponent(labelEmail4))
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Heading_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnLogin2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail1)
                    .addComponent(labelEmail4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail3)
                    .addComponent(labelEmail5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 300, 140));

        Heading_3.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        Heading_3.setForeground(new java.awt.Color(0, 113, 77));
        Heading_3.setText("Cukup untuk kamu dan hari ini");
        getContentPane().add(Heading_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        labelEmail2.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail2.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail2.setText("Donasi Makanan tersedia");
        getContentPane().add(labelEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnLogin1.setBackground(new java.awt.Color(197, 255, 236));
        btnLogin1.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(0, 175, 119));
        btnLogin1.setText("Tersedia");
        btnLogin1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 1, true));
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        Heading_4.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        Heading_4.setText("Nasi kotak + lauk");

        labelEmail6.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail6.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail6.setText("Oleh: Restauran Padang");

        btnLogin3.setBackground(new java.awt.Color(0, 175, 119));
        btnLogin3.setFont(new java.awt.Font("Lufga", 1, 14)); // NOI18N
        btnLogin3.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin3.setText("Booking");
        btnLogin3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 1, true));
        btnLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin3ActionPerformed(evt);
            }
        });

        labelEmail7.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail7.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail7.setText("Jumlah:50 porsi");

        labelEmail8.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail8.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail8.setText("JL.Ronggo Waluyo");

        labelEmail9.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail9.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail9.setText("Expired:10/11/2025");

        labelEmail10.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail10.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail10.setText("Diposting 2 jam lalu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(labelEmail8, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelEmail10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelEmail7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelEmail9)))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Heading_4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Heading_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEmail6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnLogin3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail7)
                    .addComponent(labelEmail9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail8)
                    .addComponent(labelEmail10))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 300, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnLogin6.setBackground(new java.awt.Color(197, 255, 236));
        btnLogin6.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        btnLogin6.setForeground(new java.awt.Color(0, 175, 119));
        btnLogin6.setText("Tersedia");
        btnLogin6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 1, true));
        btnLogin6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin6ActionPerformed(evt);
            }
        });

        Heading_6.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        Heading_6.setText("Kwetiau HJ,Adang");

        labelEmail16.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail16.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail16.setText("Oleh: Chef Adang");

        btnLogin7.setBackground(new java.awt.Color(0, 175, 119));
        btnLogin7.setFont(new java.awt.Font("Lufga", 1, 14)); // NOI18N
        btnLogin7.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin7.setText("Booking");
        btnLogin7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 1, true));
        btnLogin7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin7ActionPerformed(evt);
            }
        });

        labelEmail17.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail17.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail17.setText("Jumlah:20 porsi");

        labelEmail18.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail18.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail18.setText("JL.Teluk Jambe");

        labelEmail19.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail19.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail19.setText("Expired:1/12/2025");

        labelEmail20.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail20.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail20.setText("Diposting 3 jam lalu");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEmail16, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Heading_6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnLogin7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmail18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(labelEmail17)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmail19)
                            .addComponent(labelEmail20))
                        .addGap(28, 28, 28))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Heading_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEmail16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnLogin7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail17)
                    .addComponent(labelEmail19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail18)
                    .addComponent(labelEmail20))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 300, -1));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/background.jpg"))); // NOI18N
        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin2ActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin3ActionPerformed

    private void btnLogin6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin6ActionPerformed

    private void btnLogin7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new list_penerima().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Heading_2;
    private javax.swing.JLabel Heading_3;
    private javax.swing.JLabel Heading_4;
    private javax.swing.JLabel Heading_6;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnLogin2;
    private javax.swing.JButton btnLogin3;
    private javax.swing.JButton btnLogin6;
    private javax.swing.JButton btnLogin7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmail1;
    private javax.swing.JLabel labelEmail10;
    private javax.swing.JLabel labelEmail16;
    private javax.swing.JLabel labelEmail17;
    private javax.swing.JLabel labelEmail18;
    private javax.swing.JLabel labelEmail19;
    private javax.swing.JLabel labelEmail2;
    private javax.swing.JLabel labelEmail20;
    private javax.swing.JLabel labelEmail3;
    private javax.swing.JLabel labelEmail4;
    private javax.swing.JLabel labelEmail5;
    private javax.swing.JLabel labelEmail6;
    private javax.swing.JLabel labelEmail7;
    private javax.swing.JLabel labelEmail8;
    private javax.swing.JLabel labelEmail9;
    // End of variables declaration//GEN-END:variables
}
