/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dahboard = new java.awt.Panel();
        Heading = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        bg_dashboard = new javax.swing.JLabel();
        card_role = new java.awt.Panel();
        Heading_2 = new javax.swing.JLabel();
        labelRole = new javax.swing.JLabel();
        labelRole1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        panel4 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        labelRole2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dahboard.setPreferredSize(new java.awt.Dimension(320, 64));
        dahboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading.setFont(new java.awt.Font("Lufga", 1, 20)); // NOI18N
        Heading.setForeground(new java.awt.Color(255, 255, 255));
        Heading.setText("SumbangBang");
        dahboard.add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Logo_kicik.png"))); // NOI18N
        dahboard.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bg_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bg_dashboard.jpg"))); // NOI18N
        dahboard.add(bg_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 64));

        getContentPane().add(dahboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 64));

        card_role.setBackground(new java.awt.Color(0, 175, 119));
        card_role.setName(""); // NOI18N
        card_role.setPreferredSize(new java.awt.Dimension(272, 87));

        Heading_2.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        Heading_2.setForeground(new java.awt.Color(255, 255, 255));
        Heading_2.setText("Hai, ");

        labelRole.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        labelRole.setForeground(new java.awt.Color(255, 255, 255));
        labelRole.setText("Hai, ");

        javax.swing.GroupLayout card_roleLayout = new javax.swing.GroupLayout(card_role);
        card_role.setLayout(card_roleLayout);
        card_roleLayout.setHorizontalGroup(
            card_roleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_roleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(card_roleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Heading_2)
                    .addComponent(labelRole))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        card_roleLayout.setVerticalGroup(
            card_roleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_roleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Heading_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRole)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(card_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 272, 87));

        labelRole1.setBackground(new java.awt.Color(0, 113, 77));
        labelRole1.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        labelRole1.setForeground(new java.awt.Color(0, 113, 77));
        labelRole1.setText("Donasi Terbaru");
        getContentPane().add(labelRole1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel4.setBackground(new java.awt.Color(0, 113, 77));
        panel4.setPreferredSize(new java.awt.Dimension(131, 82));
        panel1.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 270, -1));

        panel3.setBackground(new java.awt.Color(0, 113, 77));
        panel3.setPreferredSize(new java.awt.Dimension(131, 82));
        panel1.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 131, -1));

        panel2.setBackground(new java.awt.Color(0, 113, 77));
        panel2.setPreferredSize(new java.awt.Dimension(131, 82));
        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 82));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 272, 174));

        labelRole2.setBackground(new java.awt.Color(0, 113, 77));
        labelRole2.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        labelRole2.setForeground(new java.awt.Color(0, 113, 77));
        labelRole2.setText("Statistik");
        getContentPane().add(labelRole2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/background.jpg"))); // NOI18N
        bg.setText("jLabel2");
        bg.setPreferredSize(new java.awt.Dimension(272, 174));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 568));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Heading_2;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg_dashboard;
    private java.awt.Panel card_role;
    private java.awt.Panel dahboard;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelRole1;
    private javax.swing.JLabel labelRole2;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    // End of variables declaration//GEN-END:variables
}
