/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.*;
import service.AuthService;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class register extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(register.class.getName());

    /**
     * Creates new form login
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Heading = new javax.swing.JLabel();
        Heading_2 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        comboTypeAccount = new javax.swing.JComboBox<>();
        labelTypeAccount = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        LinkLogin = new javax.swing.JLabel();
        labelRegister_2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading.setFont(new java.awt.Font("Lufga", 1, 20)); // NOI18N
        Heading.setForeground(new java.awt.Color(0, 113, 77));
        Heading.setText("Welcome to SumbangBang");
        getContentPane().add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        Heading_2.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        Heading_2.setForeground(new java.awt.Color(0, 113, 77));
        Heading_2.setText("Berbagi Pangan, Berbagi Harapan");
        getContentPane().add(Heading_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        labelNama.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelNama.setForeground(new java.awt.Color(142, 142, 147));
        labelNama.setText("Nama");
        getContentPane().add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        comboTypeAccount.setBackground(new java.awt.Color(255, 255, 255));
        comboTypeAccount.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        comboTypeAccount.setForeground(new java.awt.Color(0, 0, 0));
        comboTypeAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Donatur", "Penerima", "Admin" }));
        comboTypeAccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));
        comboTypeAccount.setPreferredSize(new java.awt.Dimension(272, 44));
        getContentPane().add(comboTypeAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 272, 44));

        labelTypeAccount.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelTypeAccount.setForeground(new java.awt.Color(142, 142, 147));
        labelTypeAccount.setText("Tipe Akun");
        getContentPane().add(labelTypeAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        fieldNama.setBackground(new java.awt.Color(255, 255, 255));
        fieldNama.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        fieldNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));
        fieldNama.setPreferredSize(new java.awt.Dimension(272, 44));
        getContentPane().add(fieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        fieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        fieldEmail.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        fieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));
        fieldEmail.setPreferredSize(new java.awt.Dimension(272, 44));
        getContentPane().add(fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        labelEmail.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(142, 142, 147));
        labelEmail.setText("Email");
        getContentPane().add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        labelPassword.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(142, 142, 147));
        labelPassword.setText("Password");
        getContentPane().add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        fieldPassword.setBackground(new java.awt.Color(255, 255, 255));
        fieldPassword.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        fieldPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)));
        fieldPassword.setPreferredSize(new java.awt.Dimension(272, 44));
        getContentPane().add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 270, -1));

        btnRegister.setBackground(new java.awt.Color(0, 175, 119));
        btnRegister.setFont(new java.awt.Font("Lufga", 1, 16)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(224, 224, 224), 1, true));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 272, 41));

        LinkLogin.setFont(new java.awt.Font("Lufga", 1, 12)); // NOI18N
        LinkLogin.setForeground(new java.awt.Color(0, 113, 77));
        LinkLogin.setText("Login di sini");
        LinkLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LinkLoginMouseClicked(evt);
            }
        });
        getContentPane().add(LinkLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, -1));

        labelRegister_2.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        labelRegister_2.setForeground(new java.awt.Color(142, 142, 147));
        labelRegister_2.setText("Sudah Punya Akun?");
        getContentPane().add(labelRegister_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/background.jpg"))); // NOI18N
        bg.setText("jLabel2");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // 1. Ambil data dari form
        String role = (String) comboTypeAccount.getSelectedItem();
        String nama = fieldNama.getText().trim();
        String email = fieldEmail.getText().trim();
        String pass = new String(fieldPassword.getPassword());
        
        // Default value untuk field spesifik
        String phone = "08123456789"; // Sementara dummy atau tambah field di UI
        String address = "Alamat Default"; // Sementara dummy atau tambah field di UI

        // 2. Validasi Input Dasar
        if (nama.isEmpty() || email.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Siapkan Objek User Berdasarkan Role
        User newUser = null;
        
        // PENERIMA & ADMIN -> Sesuai logika database
        if (role.equalsIgnoreCase("Donatur")) {
            // Parameter: userId(null), name, email, password(null dulu), phone, address, businessType
            newUser = new Donatur(null, nama, email, null, phone, address, "Perorangan"); 
        } else if (role.equalsIgnoreCase("Penerima")) {
            // Parameter: userId(null), name, email, password(null dulu), phone, address, recipientType
            newUser = new Penerima(null, nama, email, null, phone, address, "Umum");
        } else if (role.equalsIgnoreCase("Admin")) {
             // Parameter: userId(null), name, email, password(null dulu), phone, address
            newUser = new Admin(null, nama, email, null, phone, address);
        }

        // 4. Panggil Service untuk Register
        if (newUser != null) {
            AuthService authService = new AuthService();
            boolean success = authService.register(newUser, pass); // Password asli dikirim untuk di-hash

            if (success) {
                JOptionPane.showMessageDialog(this, "Registrasi Berhasil! Silakan Login.");
                Navigator.toLogin(this); // Pindah ke layar login
            } else {
                JOptionPane.showMessageDialog(this, "Registrasi Gagal. Email mungkin sudah terdaftar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void LinkLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinkLoginMouseClicked
        Navigator.toLogin(this);
    }//GEN-LAST:event_LinkLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel Heading_2;
    private javax.swing.JLabel LinkLogin;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> comboTypeAccount;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelRegister_2;
    private javax.swing.JLabel labelTypeAccount;
    // End of variables declaration//GEN-END:variables
}
