/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.User;
import model.Donatur;
import model.Penerima;
/**
 *
 * @author User
 */
public class UserProfile extends javax.swing.JFrame {
    private User currentUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserProfile.class.getName());

    /**
     * Creates new form UserProfile
     */
    public UserProfile() {
        initComponents();
    }
    public UserProfile(User user) {
        initComponents();
        this.currentUser = user;
        
        setupProfileData();
        setLocationRelativeTo(null);
    }
    private void setupProfileData() {
        if (currentUser != null) {
            // 1. Isi Data Dasar
            txtName.setText(currentUser.getName());
            txtEmail.setText(currentUser.getEmail());
            txtPhone.setText(currentUser.getPhone());
            txtAddress.setText(currentUser.getAddress());
            
            // 2. Logika Deteksi Role yang Lebih Detail
            String roleDisplay = currentUser.getRole();
            
            if (currentUser instanceof Donatur) {
                Donatur d = (Donatur) currentUser;
                if (d.getBusinessType() != null) {
                    roleDisplay += " - " + d.getBusinessType(); // Contoh: "DONATUR - Restoran"
                }
            } else if (currentUser instanceof Penerima) {
                Penerima p = (Penerima) currentUser;
                if (p.getRecipientType() != null) {
                    roleDisplay += " - " + p.getRecipientType(); // Contoh: "PENERIMA - Panti Asuhan"
                }
            }
            
            txtRole.setText(roleDisplay);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        dahboard = new java.awt.Panel();
        Heading1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        bg_dashboard = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        headingDetail = new javax.swing.JLabel();
        food = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        CardProfile = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dahboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading1.setFont(new java.awt.Font("Lufga", 1, 20)); // NOI18N
        Heading1.setForeground(new java.awt.Color(255, 255, 255));
        Heading1.setText("SumbangBang");
        dahboard.add(Heading1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Logo_kicik.png"))); // NOI18N
        dahboard.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bg_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bg_dashboard.jpg"))); // NOI18N
        dahboard.add(bg_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 64));

        getContentPane().add(dahboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 64));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        btnBack.setText("jLabel3");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 30, 30));

        headingDetail.setFont(new java.awt.Font("Lufga", 1, 20)); // NOI18N
        headingDetail.setForeground(new java.awt.Color(0, 175, 119));
        headingDetail.setText("Profile");
        getContentPane().add(headingDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 30));

        food.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/food.jpg"))); // NOI18N
        getContentPane().add(food, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 60));

        txtRole.setEditable(false);
        txtRole.setBackground(new java.awt.Color(255, 255, 255));
        txtRole.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        txtRole.setForeground(new java.awt.Color(0, 153, 102));
        txtRole.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRole.setText(" ");
        txtRole.setBorder(null);
        getContentPane().add(txtRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 280, 30));

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Lufga", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 153, 102));
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.setText(" ");
        txtName.setBorder(null);
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 280, 30));

        CardProfile.setBackground(new java.awt.Color(255, 255, 255));
        CardProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Email: ");

        jLabel2.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Telepon: ");

        jLabel3.setFont(new java.awt.Font("Lufga", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Alamat: ");

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 102, 102));
        txtEmail.setText(" ");
        txtEmail.setBorder(null);

        txtPhone.setEditable(false);
        txtPhone.setBackground(new java.awt.Color(255, 255, 255));
        txtPhone.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(0, 102, 102));
        txtPhone.setText(" ");
        txtPhone.setBorder(null);

        txtAddress.setEditable(false);
        txtAddress.setBackground(new java.awt.Color(255, 255, 255));
        txtAddress.setFont(new java.awt.Font("Lufga", 0, 12)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(0, 102, 102));
        txtAddress.setText(" ");
        txtAddress.setBorder(null);

        javax.swing.GroupLayout CardProfileLayout = new javax.swing.GroupLayout(CardProfile);
        CardProfile.setLayout(CardProfileLayout);
        CardProfileLayout.setHorizontalGroup(
            CardProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CardProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardProfileLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CardProfileLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CardProfileLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        CardProfileLayout.setVerticalGroup(
            CardProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardProfileLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(CardProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(CardProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(CardProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 294, 280, 120));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/background.jpg"))); // NOI18N
        bg.setText("jLabel2");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        if (currentUser.getRole().equalsIgnoreCase("DONATUR")) {
            new DashboardDonatur(currentUser).setVisible(true);
        } else if (currentUser.getRole().equalsIgnoreCase("PENERIMA")) {
            new DashboardPenerima(currentUser).setVisible(true);
        } else {
            // Jaga-jaga kalau Admin
            new DashboardAdmin(currentUser).setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserProfile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardProfile;
    private javax.swing.JLabel Heading1;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg_dashboard;
    private javax.swing.JLabel btnBack;
    private java.awt.Panel dahboard;
    private javax.swing.JLabel food;
    private javax.swing.JLabel headingDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRole;
    // End of variables declaration//GEN-END:variables
}
